test:
  nickname: DolphaGo

---

spring:
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        #      show_sql: true # 쿼리 콘솔 출력 -> 사용 지양
        format_sql: true
        default_batch_fetch_size: 1000 # 하이버네이트 최적화

  datasource:
    url: jdbc:h2:tcp://localhost/~/test
    username: sa
    password:
    driver-class-name: org.h2.Driver
  output:
    ansi:
      enabled: always

logging:
  level:
    org.hibernate.SQL: debug # 쿼리 로그 출력
#    org.hibernate.type.descriptor.sql: trace
